### ISSUE TITLE
Drive with Gyro & PID in Teleop

### ISSUE THREAD

**Issue by benjamin-antupit** [Gryphon-Robotics-4990/2018#21]
Make the robot drive accurately in teleop with feedback from AHRS using a PID loop.

### Stage 1: throtte ≠ 0, turnSteepness = 0 (robot goes straight)
See [GyroStraight](https://github.com/Gryphon-Robotics-4990/2018/blob/master/src/main/java/org/usfirst/frc/team4990/robot/commands/GyroStraight.java)
- [x] make the structure
- [x] test on the robot
- [x] tune P, I and D constants

### Stage 2: throttle = 0, turnSteepness ≠ 0 (robot turns in place)
See [GyroTurn](https://github.com/Gryphon-Robotics-4990/2018/blob/master/src/main/java/org/usfirst/frc/team4990/robot/commands/GyroTurn.java)
- [x] make the structure
- [ ] test on robot
- [ ] tune P, I and D constants

### Stage 3: throttle ≠ 0, turnSteepness ≠ 0 (robot arc turns)
This function will need to predict the change in heading based on controller input and then stay on the heading using a PID loop with the AHRS as the source. 
- [x] make the structure
- [ ] test on robot
- [ ] tune P, I and D constants

**Comment by benjamin-antupit** [comment]
See TeleopArcadeDrive.java in Master for information. This was started in the teleopStraightDrive-PIDturnController branch, but it is not important now.

**Comment by benjamin-antupit** [comment]
We added pid-based autonomus driving, so we should be able to adapt that to teleop

**Comment by benjamin-antupit** [comment]
See branch Teleop-PIDDrive and new PIDDriveTrainController class.

**Comment by benjamin-antupit** [comment]
Let's forget about this for now. It would take a lot of development time to complete and it's not worth it right now. We can work on it later if it's still a priority.
